import './globals.css'
import type { Metadata } from 'next'
import { Ubuntu } from 'next/font/google'

const inter = Ubuntu({ weight: '300', style: 'normal' }) // ojo a las fuentes que coges y las propiedades obligatorias

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
