import type { Metadata } from "next";

import { Inter } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Provider store={store}> */}
        {/* el provider solo puede ser desde el lado del cliente por eso revienta si no se hace pero para no hacer toda la app 'use client' pero el problea está en que solo ciertos componentes de NExt pueden ser cllient side por ende, aquí no se debe poner el provider. Se tiene que poner en una layer muy alta pero no aquí. Lo hago a parte en el store/providers*/}
        {children}
        {/* </Provider> */}
      </body>
    </html>
  );
}
